#!/usr/bin/env node
'use strict';

// Clones avelor-es/homebrew-floo, writes an updated Formula/floo.rb, and pushes.
// Called by the release workflow after binaries are uploaded to GitHub Releases.
// Requires env vars: VERSION, SHA_LINUX_X64, SHA_LINUX_ARM64,
//                    SHA_DARWIN_X64, SHA_DARWIN_ARM64, GH_TOKEN

const fs   = require('fs');
const os   = require('os');
const path = require('path');
const { execSync } = require('child_process');

const {
  VERSION,
  SHA_LINUX_X64,
  SHA_LINUX_ARM64,
  SHA_DARWIN_X64,
  SHA_DARWIN_ARM64,
  GH_TOKEN,
} = process.env;

const missing = ['VERSION', 'SHA_LINUX_X64', 'SHA_LINUX_ARM64', 'SHA_DARWIN_X64', 'SHA_DARWIN_ARM64', 'GH_TOKEN']
  .filter(k => !process.env[k]);
if (missing.length) {
  process.stderr.write('error: missing env vars: ' + missing.join(', ') + '\n');
  process.exit(1);
}

const ver = VERSION.replace(/^v/, '');
const base = `https://github.com/avelor-es/floo/releases/download/${VERSION}`;
const tapRepo = `https://x-access-token:${GH_TOKEN}@github.com/avelor-es/homebrew-floo.git`;

const formula = `# Auto-generated by the floo release workflow — do not edit manually.
class Floo < Formula
  desc "Deploy from anywhere — floo agent + token-scoped deploy CLI"
  homepage "https://github.com/avelor-es/floo"
  version "${ver}"
  license "MIT"

  on_macos do
    on_arm do
      url "${base}/floo-darwin-arm64"
      sha256 "${SHA_DARWIN_ARM64}"
    end
    on_intel do
      url "${base}/floo-darwin-x64"
      sha256 "${SHA_DARWIN_X64}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/floo-linux-arm64"
      sha256 "${SHA_LINUX_ARM64}"
    end
    on_intel do
      url "${base}/floo-linux-x64"
      sha256 "${SHA_LINUX_X64}"
    end
  end

  def install
    bin.install Dir["floo-*"].first => "floo"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/floo --version")
  end
end
`;

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'floo-tap-'));

try {
  execSync(`git clone --depth 1 "${tapRepo}" "${tmp}"`, { stdio: 'inherit' });
  fs.mkdirSync(path.join(tmp, 'Formula'), { recursive: true });
  fs.writeFileSync(path.join(tmp, 'Formula', 'floo.rb'), formula, 'utf8');

  execSync('git config user.email "bot@avelor.es"', { cwd: tmp });
  execSync('git config user.name "floo-bot"', { cwd: tmp });
  execSync('git add Formula/floo.rb', { cwd: tmp });
  execSync(`git commit -m "floo ${VERSION}"`, { cwd: tmp });
  execSync('git push', { cwd: tmp, stdio: 'inherit' });

  process.stdout.write('homebrew tap updated to ' + VERSION + '\n');
} finally {
  fs.rmSync(tmp, { recursive: true, force: true });
}
